apiVersion: v1
kind: Service
metadata:
  name: swe645-hw3-survey-service
spec:
  type: NodePort
  selector:
    app: swe645-hw3-survey
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
    - name: frontend
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081